### ISSUE TITLE
Command line options for updating silently

### ISSUE THREAD

**Issue by LegzRwheelz** [Chopper1337/XeniaUpdater#8]
Hi, as the title suggests, I would love to see support for command line arguments for silently updating.

**Describe the solution you'd like**
Some kind of command line implementation for updating Xenia silently through CMD or PowerShell. Ideally, we would set the working directory, where the Xenia executable is located so that the updater tool knows where to place the exe instead of creating a folder titled "XeniaMaster" and "XeniaCanary". 

Ideally, this would be used to create a task in task scheduler in Windows.

Another idea would be to have an option to run this updater at system start and have it quietly check for updates from the system tray with the ability to tell it how frequently we want it to check for updates (hourly, daily, weekly, bi-weekly, monthly). Maybe offering options for both. ie: creating a task in task scheduler and/or running from the system tray.

**Additional context**
I am among the many users of the amazing frontend, LaunchBox. Use LaunchBox users tend to automate nearly everything to keep the computer as appliance-like as possible whine letting our emulators up-to-date while using LaunchBox I use it as the shell for our PCs (instead of Windows explorer) and we only have gamepads out arcade sticks connected for navigation of the system and only use a kb/m for servicing the system, frontend and emulators. Well due to the age of Xenia, Yuzu and a few other emus they are frequently getting updates and their performance ever increasing, we need to keep these emus as up-to-date as possible but it kinda kills the appliance-like experience and creates additional windows for downtime. So being able to keep Xenia automatically as well as silently updated, would be a great feature to have and would placate a somewhat large group of users and is something I think all most users would welcome.

For some ideas on possible parameters [Here](https://github.com/amakvana/EzYuzu/blob/master/GUIDE.md#command-line-interface-options) is another update tool, it is used with Yuzu. Lol you can even see where I asked basically the same question.

**Comment by Chopper1337** [comment]
Initially, Xenia Updater was a PowerShell script. I haven't tested this, but here's the original script with the download URL updated: https://gist.github.com/Chopper1337/9b93b4dba9ba0652d88ac27691afadd3

Again, this hasn't been tested and I also can't remember the reason I moved away from using that script but I'm sure there was one.

**Comment by Chopper1337** [comment]
I've made a fairly basic CLI version of Xenia Updater called [XeniaLauncher-CLI](https://github.com/Chopper1337/XeniaLauncher-CLI).

I've tested this with Task Scheduler and one thing to note is that you must specify the "Start in" path as the path where you'd like the "XeniaCanary" and "XeniaMaster" folders to be created.

![image](https://github.com/Chopper1337/XeniaUpdater/assets/43015696/237e8d80-e1c7-4da8-9250-fb3c0d0154db)

In this example, it should update the master build of Xenia and output the `XeniaMaster` folder to `C:\Users\Admin\Desktop\Xenia Builds\`

You can add multiple actions to the same task so that should allow you to update both builds in the case you use both.

I would have added command line arguments to this version of Xenia Updater but the code is just not easy to work with. Any further work for a GUI updater will be made on [XeniaUpdater2](https://github.com/Chopper1337/XeniaUpdater2) which will eventually be renamed to Xenia Launcher

**Comment by LegzRwheelz** [comment]
Thank you for the help, this little tool works flawlessly. I can set it to update at 3am or some ungodly hour that the htpc is not in use so I never have to see the console window. I am intrigued by your new tool though, Xenia Updater 2. Are you going to be implementing arguments for silent updates to the new launcher? Thanks again!

**Comment by LegzRwheelz** [comment]
### am sorry if I am being a pest but is there a way to make the console window invisible?
